gazebo_ros_control/pid_gains:
  iiwa_joint_1:  {p: 700,  i: 0.01, d: 100}
  iiwa_joint_2:  {p: 10000,  i: 100, d: 100}
  iiwa_joint_3: {p: 4500,  i: 35, d: 1}
  iiwa_joint_4:  {p: 5500,  i: 60, d: 2}
  iiwa_joint_5: {p: 1000,  i: 30, d: 0.01}
  iiwa_joint_6:  {p: 500,  i: 0.1, d: 0.01}
  iiwa_joint_7: {p: 100,  i: 0.1, d: 0.01}