# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500  # in Hz

# Default Controllers ------------------------------------------------
TorqueController:
  type: effort_controllers/JointGroupEffortController
  joints:
    - $(arg robot_name)_joint_1
    - $(arg robot_name)_joint_2
    - $(arg robot_name)_joint_3
    - $(arg robot_name)_joint_4
    - $(arg robot_name)_joint_5
    - $(arg robot_name)_joint_6
    - $(arg robot_name)_joint_7

PositionTorqueController:
  type: effort_controllers/JointGroupPositionController
  joints:
    - $(arg robot_name)_joint_1
    - $(arg robot_name)_joint_2
    - $(arg robot_name)_joint_3
    - $(arg robot_name)_joint_4
    - $(arg robot_name)_joint_5
    - $(arg robot_name)_joint_6
    - $(arg robot_name)_joint_7
  $(arg robot_name)_joint_1:
    pid: {p: 800.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
  $(arg robot_name)_joint_2:
    pid: {p: 800.0, i: 1000, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}
  $(arg robot_name)_joint_3:
    pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
  $(arg robot_name)_joint_4:
    pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
  $(arg robot_name)_joint_5:
    pid: {p: 300.0, i: 5, d: 10.0, i_clamp_min: -10000, i_clamp_max: 10000}
  $(arg robot_name)_joint_6:
    pid: {p: 50.0, i: 1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000} #p = 50, i = 1, d = 1.0
  $(arg robot_name)_joint_7:
    pid: {p: 10.0, i: 0.1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000} #p = 10, i = 0.1, d = 1.0

PositionController:
  type: position_controllers/JointGroupPositionController
  joints:
    - $(arg robot_name)_joint_1
    - $(arg robot_name)_joint_2
    - $(arg robot_name)_joint_3
    - $(arg robot_name)_joint_4
    - $(arg robot_name)_joint_5
    - $(arg robot_name)_joint_6
    - $(arg robot_name)_joint_7

# Custom Controllers ------------------------------------------------
# The space variable can be either set to "task" or "joint"
CustomControllers:
  type: iiwa_control/CustomEffortController
  joints:
    - $(arg robot_name)_joint_1
    - $(arg robot_name)_joint_2
    - $(arg robot_name)_joint_3
    - $(arg robot_name)_joint_4
    - $(arg robot_name)_joint_5
    - $(arg robot_name)_joint_6
    - $(arg robot_name)_joint_7
  params:
    space: task
    # end_effector is only needed in task space
    end_effector: $(arg robot_name)_link_ee
    null_space:
      joints: [0.044752691045324394, 0.6951627023357917, -0.01416978801753847, -1.0922311725109015, -0.0050429618456282, 1.1717338014778385, -0.01502630060305613]
      Kp: 20. 
      Kd: 0.1 #0.1 
      max_torque: 10.
  controllers:
    # ForceDS: {type: "ForceModDSController", params: [200]}
    # #PD: {type: "PidController", params: [20., 2.], input: "Orientation", output: "Torque"} #20, 2
    # LinearDS: {type: "LinearDSController", params: [1., 1., 1.]}
    PassiveDS: {type: "PassiveDSController", params: [200, 200]} #200, 200
    PD: {type: "PidController", params: [80., 2.], input: "Orientation", output: "Torque"} #20, 2 // 80, 2
    #PD: {type: "PidController", params: [20., 2.], input: "AngularVelocity", output: "Torque"} #20, 2

     # LinearDS: {type: "LinearDSController", params: [1., 1., 1.]}
  #     PDPosition: {type: "PidController", params: [20., 2.], input: "Position|Velocity", output: "Force"}
  #     PDOrientation: {type: "PidController", params: [20., 2.], input: "Orientation|AngularVelocity", output: "Torque"}
  # structure:
  #   AddCtrl:
  #     - PDPosition
  #     - PDOrientation

  # structure:
  #   AddCtrl:
  #     - PDPosition
  #     - PDOrientation

  # structure:
    #  AddCtrl:
    #    - LinearDS
    #    - ForceDS
    # CascadeCtrl:
    #   - LinearDS
    #   - PassiveDS

# PositionTrajectoryController:
#   type: position_controllers/JointTrajectoryController
#   joints: 
#     - $(arg robot_name)_joint_1
#     - $(arg robot_name)_joint_2
#     - $(arg robot_name)_joint_3
#     - $(arg robot_name)_joint_4
#     - $(arg robot_name)_joint_5
#     - $(arg robot_name)_joint_6
#     - $(arg robot_name)_joint_7

#   constraints:
#     goal_time: 0.5                   # Override default

#   state_publish_rate:  25            # Override default
#   action_monitor_rate: 30            # Override default
#   stop_trajectory_duration: 0        # Override default

