# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500  # in Hz

# Default Controllers ------------------------------------------------
TorqueController:
  type: effort_controllers/JointGroupEffortController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7

PositionTorqueController:
  type: effort_controllers/JointGroupPositionController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  iiwa_joint_1:
    pid: {p: 800.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
  iiwa_joint_2:
    pid: {p: 800.0, i: 1000, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}
  iiwa_joint_3:
    pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
  iiwa_joint_4:
    pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
  iiwa_joint_5:
    pid: {p: 300.0, i: 5, d: 10.0, i_clamp_min: -10000, i_clamp_max: 10000}
  iiwa_joint_6:
    pid: {p: 50.0, i: 1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}
  iiwa_joint_7:
    pid: {p: 10.0, i: 0.1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}

PositionController:
  type: position_controllers/JointGroupPositionController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7

# Custom Controllers ------------------------------------------------
# The space variable can be either set to "task" or "joint"
CustomControllers:
  type: iiwa_control/CustomEffortController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  params:
    space: task
    # end_effector is only needed in task space
    end_effector: iiwa_link_ee
  controllers:
    LinearDS: {type: "LinearDSController", params: [1., 1., 1.]}
    PassiveDS: {type: "PassiveDSController", params: [200, 200]}
    PD: {type: "PidController", params: [20., 2.], input: "Orientation", output: "Torque"}
  structure:
    CascadeCtrl:
      - LinearDS
      - PassiveDS
